<a href="https://www.kaggle.com/code/sovankumardas/day-2-05-04-2022?scriptVersionId=92173902" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np 
import pandas as pd
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


In [2]:
arr1 = np.empty((3,3))
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The printing 3x3 matrix is: ")
print(arr2)
arr3 = np.ones((2,3))
print("The printing 3x3 1 matrix is: ")
print(arr3)
arr4 = np.zeros((3,3))
print("The printing 3x3 0 matrix is: ")
print(arr4)
arr5=np.random.random((3,3))
print("The printing 3x3 matrix with random values: ")
print(arr5)

The printing 3x3 matrix is: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The printing 3x3 1 matrix is: 
[[1. 1. 1.]
 [1. 1. 1.]]
The printing 3x3 0 matrix is: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The printing 3x3 matrix with random values: 
[[0.29695983 0.91386857 0.75604686]
 [0.25277127 0.30824379 0.40724857]
 [0.7889648  0.17832751 0.52838247]]


In [3]:
var1=np.empty(5)
var1[0]=5.55
var1[1]=5
var1[2]=96
var1[3]=21
var1[4]=1.23
print(var1)
print("The dimension of the array ...")
print(var1.shape)
print("The size of the array ...")
print(var1.size)

[ 5.55  5.   96.   21.    1.23]
The dimension of the array ...
(5,)
The size of the array ...
5


In [4]:
var3 = np.empty((2,3))
var3[0][0] = 9
var3[0][1] = 2.36
var3[0][2] = 5.6
var3[1][0] = 0.9
var3[1][1] = 1.32
var3[1][2] = 56
print(var3)
print("The dimension of the array ...")
print(var3.shape)
print(var3[1])
print(var3[[0, 1]])
print(var3[:, 2])
print(var3[:, [1, 2]])
print(var3[1][2])

print("Transpose of the matrix....")
print(np.transpose(var3))
print("Re-Shaped the array....")
print(var3.reshape(3,2))


[[ 9.    2.36  5.6 ]
 [ 0.9   1.32 56.  ]]
The dimension of the array ...
(2, 3)
[ 0.9   1.32 56.  ]
[[ 9.    2.36  5.6 ]
 [ 0.9   1.32 56.  ]]
[ 5.6 56. ]
[[ 2.36  5.6 ]
 [ 1.32 56.  ]]
56.0
Transpose of the matrix....
[[ 9.    0.9 ]
 [ 2.36  1.32]
 [ 5.6  56.  ]]
Re-Shaped the array....
[[ 9.    2.36]
 [ 5.6   0.9 ]
 [ 1.32 56.  ]]


In [5]:
Arr_1= np.empty((2,3))
Arr_1[0][0] = 1
Arr_1[0][1] = 2
Arr_1[0][2] = 3
Arr_1[1][0] = 4
Arr_1[1][1] = 5
Arr_1[1][2] = 6

Arr_2 = np.empty((1,3))
Arr_2[0][0] = 10
Arr_2[0][1] = 20
Arr_2[0][2] = 30

Arr_Con = np.concatenate((Arr_1, Arr_2), axis = 0)
print(Arr_Con)

print("The min value in the concatenate matrix is: ")
print(Arr_Con.min())
print("The max value in the concatenate matrix is: ")
print(Arr_Con.max())
print("Cumulative sum of the values stored in an array")
print(Arr_Con.cumsum())
print("Mean or average value stored in an array")
print(Arr_Con.mean())
print("standard deviation of values stored in an array")
print(Arr_Con.std())

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [10. 20. 30.]]
The min value in the concatenate matrix is: 
1.0
The max value in the concatenate matrix is: 
30.0
Cumulative sum of the values stored in an array
[ 1.  3.  6. 10. 15. 21. 31. 51. 81.]
Mean or average value stored in an array
9.0
standard deviation of values stored in an array
9.201449161228174


In [6]:
from numpy import pi
arr1 = np.array([10,20,30])
np.sin(arr1*np.pi/100)

array([0.30901699, 0.58778525, 0.80901699])

In [7]:
arr2 = np.array([1.1,2,2,10,20,30,50,5.5,8])
print(arr2)
print(np.around(arr2))
print(np.around(arr2,decimals=5))
print(np.floor(arr2))
print(np.ceil(arr2))

[ 1.1  2.   2.  10.  20.  30.  50.   5.5  8. ]
[ 1.  2.  2. 10. 20. 30. 50.  6.  8.]
[ 1.1  2.   2.  10.  20.  30.  50.   5.5  8. ]
[ 1.  2.  2. 10. 20. 30. 50.  5.  8.]
[ 2.  2.  2. 10. 20. 30. 50.  6.  8.]


In [8]:
arr = np.array([[8,2,1],[14,5,26]])
print(np.sort(arr))
print("The values with axis 0....")
print(np.sort(arr, axis = 0))
print("The values with axis 1....")
print(np.sort(arr, axis = 1))
print("The values in the matrix which are greater than 5.")
print(arr[np.where(arr>5)])

[[ 1  2  8]
 [ 5 14 26]]
The values with axis 0....
[[ 8  2  1]
 [14  5 26]]
The values with axis 1....
[[ 1  2  8]
 [ 5 14 26]]
The values in the matrix which are greater than 5.
[ 8 14 26]


In [9]:
arr = np.array([[8,2,1],[14,5,26],[10,56,1]])
print("The mean of the array is: ")
print(np.mean(arr))
print("The mean of the array with axis 0 is: ")
print(np.mean(arr,axis=0))
print("The mean of the array with axis 1 is: ")
print(np.mean(arr,axis=1))
print("The S.D of the array with is: ")
print(np.std(arr))
print(np.var(arr))

The mean of the array is: 
13.666666666666666
The mean of the array with axis 0 is: 
[10.66666667 21.          9.33333333]
The mean of the array with axis 1 is: 
[ 3.66666667 15.         22.33333333]
The S.D of the array with is: 
16.73983937265296
280.22222222222223
